# Site settings
title: Burgiblog
name: "Burkhard Reffeling"
email:
description: "I'm a 20-something Software Engineer from Leeds, UK. I write about technology."
baseurl: ""
url: "http://burgiblog.com"
twitter_username: BurkhardR
github_username:  hardchor

# Build settings
markdown: kramdown
permalink: pretty
